name = "HexMC"
author = "HexMC Contributors"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55fb5ffd7584e039b980e3f77aba9f99199fe128a700479c74613846ccb8d683"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
